# Generated by Django 3.0.7 on 2022-07-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='destination',
            new_name='designation',
        ),
    ]
