# Generated by Django 4.0.6 on 2022-09-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Trip',
        ),
    ]
